# Generated by Django 2.2.7 on 2019-11-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
    ]
