# Generated by Django 2.2.7 on 2019-11-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoAccesorio', models.CharField(choices=[('ca', 'Casco'), ('pe', 'Peto'), ('ma', 'Manoplas'), ('pa', 'Pantalones'), ('gr', 'Grebas'), ('an', 'Anillo')], max_length=10)),
                ('tier', models.IntegerField(default=0)),
                ('vida_extra', models.IntegerField()),
                ('daño_extra', models.FloatField()),
                ('defensa_extra', models.FloatField()),
                ('costo_puntos', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Clase_Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('vida_base', models.IntegerField()),
                ('daño_base', models.FloatField()),
                ('defensa_base', models.FloatField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('vida', models.IntegerField()),
                ('daño', models.FloatField()),
                ('defensa', models.FloatField()),
                ('imagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='EnemigoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=150)),
                ('vida', models.IntegerField()),
                ('daño', models.FloatField()),
                ('defensa', models.FloatField()),
                ('imagen', models.CharField(default='Inserte url imagen', max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Posion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('vida', models.IntegerField(default=0)),
                ('daño', models.FloatField(default=0)),
                ('imagen', models.CharField(default='Inserte url imagen', max_length=2083)),
                ('costo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('descuento', models.FloatField(default=0, max_length=3)),
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('puntos', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.FloatField(default=0)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='PosionPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Posion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_total', models.IntegerField(default=0)),
                ('vida_actual', models.IntegerField(default=0)),
                ('daño_total', models.FloatField(default=0)),
                ('defensa_total', models.FloatField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('total_puntos', models.FloatField(default=0)),
                ('accesorios', models.ManyToManyField(blank=True, to='tienda.Accesorio')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Clase_Personaje')),
                ('enemigoAsignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.EnemigoAsignado')),
                ('posion', models.ManyToManyField(blank=True, null=True, to='tienda.PosionPerfil')),
                ('recompensa', models.ManyToManyField(blank=True, to='tienda.Recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarroProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('preciototal', models.FloatField(default=0)),
                ('totalpuntos', models.FloatField(default=0)),
                ('items', models.ManyToManyField(to='tienda.CarroProducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
