# Generated by Django 2.2.6 on 2019-11-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoAccesorio', models.CharField(max_length=30)),
                ('vida_extra', models.IntegerField()),
                ('daño_extra', models.FloatField()),
                ('defensa_extra', models.FloatField()),
                ('costo_puntos', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Clase_Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('vida_base', models.IntegerField()),
                ('daño_base', models.FloatField()),
                ('defensa_base', models.FloatField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('descuento', models.FloatField(default=0, max_length=3)),
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('puntos', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje_Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Accesorio')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('total_puntos', models.FloatField()),
                ('accesorios', models.ManyToManyField(to='tienda.Personaje_Accesorio')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Clase_Personaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarroProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('preciototal', models.FloatField()),
                ('totalpuntos', models.FloatField()),
                ('items', models.ManyToManyField(to='tienda.CarroProducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
