# Generated by Django 2.2.6 on 2019-10-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('costo_puntos', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Clase_Personaje',
            fields=[
                ('id_clase', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('vida_base', models.IntegerField()),
                ('daño_base', models.FloatField()),
                ('evasion_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Clase_Personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('urlImagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Accesorio',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('daño', models.IntegerField()),
                ('defensa', models.IntegerField()),
                ('critico', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('evasion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje_Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_accesorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Accesorio')),
                ('id_personaje', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Personaje')),
            ],
        ),
        migrations.AddField(
            model_name='personaje',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('sub_puntos', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('final_compra', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Carrito')),
            ],
        ),
        migrations.AddField(
            model_name='accesorio',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Tipo_Accesorio'),
        ),
    ]
