# Generated by Django 2.2.6 on 2019-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descuento',
            field=models.FloatField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
