# Generated by Django 2.2.6 on 2019-11-14 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('total_puntos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.BooleanField(default=0)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Productos')),
            ],
        ),
        migrations.RenameModel(
            old_name='Personaje_Accesorio',
            new_name='Perfil_Accesorio',
        ),
        migrations.DeleteModel(
            name='Personaje',
        ),
        migrations.AddField(
            model_name='perfil',
            name='accesorios',
            field=models.ManyToManyField(to='tienda.Perfil_Accesorio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.Clase_Personaje'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recompensa',
            field=models.ManyToManyField(to='tienda.Recompensa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
