# Generated by Django 2.2.7 on 2019-11-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_recompensa_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='nuevoPrecio',
            field=models.FloatField(default=0),
        ),
    ]
