# Generated by Django 2.2.6 on 2019-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20191114_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recompensa',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
