# Generated by Django 2.2.6 on 2019-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20191114_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preciototal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='totalpuntos',
            field=models.FloatField(default=0),
        ),
    ]
