# Generated by Django 2.2.6 on 2019-11-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20191115_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.CarroProducto'),
        ),
    ]
