# Generated by Django 2.2.6 on 2019-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20191115_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='items',
        ),
        migrations.AddField(
            model_name='carro',
            name='items',
            field=models.ManyToManyField(to='tienda.CarroProducto'),
        ),
    ]
