# Generated by Django 2.2.6 on 2019-11-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20191115_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='clase',
        ),
    ]
