# Generated by Django 2.2.3 on 2019-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_auto_20191118_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='accesorios',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.Accesorio'),
        ),
        migrations.DeleteModel(
            name='Perfil_Accesorio',
        ),
    ]
