# Generated by Django 2.2.6 on 2019-11-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_auto_20191118_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='daño_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='defensa_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='vida_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='accesorios',
            field=models.ManyToManyField(blank=True, to='tienda.Accesorio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='recompensa',
            field=models.ManyToManyField(blank=True, to='tienda.Recompensa'),
        ),
    ]
