# Generated by Django 2.2.7 on 2019-11-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_auto_20191124_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemigo',
            name='imagen',
            field=models.CharField(default=0, max_length=2083),
            preserve_default=False,
        ),
    ]
