# Generated by Django 2.2.7 on 2019-11-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_enemigo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemigo',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
